---
- name: clone tup
  git:
    repo="https://github.com/gittup/tup.git"
    dest="{{ dir.tool }}/tup"

- name: build tup
  shell: sh ./bootstrap.sh
  args:
    chdir: "{{ dir.tool }}/tup"

- name: clean tup directory
  file:
    path="{{ dir.tool }}/tup/build"
    state=absent

- name: install tup
  file:
    src="{{ dir.tool }}/tup/tup"
    dest="/usr/bin/tup"
    force=yes
    state=link
